title: OpenMage LTS Developer Documentation
logo: DevDocs
description: OpenMage LTS Developer Documentation.

url: https://dford-avb.github.io

lsi: false
safe: true
source: /home/dford/dford-avb.github.io 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#############
# Variables #
#############
#
# 1.x variables
m1xgdeurl: http://dford-avb.github.io
m1xgithuburl: https://github.com/dford-avb/devdocs/blob/master/

##########
# Ignore #
##########
#
# The path patterns excluded during site generation
#
exclude:
  - scss
  - bin
  - node_modules
  - vendor
  - .git
  - .idea
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - Rakefile
  - rakelib
  - README.md
  - _plugins
